---
services:
  hyper-mcp-search:
    image: ghcr.io/tuananh/hyper-mcp:v0.1.6
    command: --config-file=/tmp/config.yml
    restart: unless-stopped
    networks:
      - searxng
    environment:
      HYPER_MCP_TRANSPORT: sse
      HYPER_MCP_BIND_ADDRESS: "0.0.0.0:3001"
    ports:
      - "3001:3001"
    volumes:
      - ./config.yml:/tmp/config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:

volumes:
  valkey-data:
  searxng-data:
